name: Build and Release Debian Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Debian Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up the build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Build the Debian package
      run: |
        cd code-wayland
        debuild -us -uc -b

    - name: Get Debian package filename
      id: get_filename
      run: |
        FILE_NAME=$(find . -maxdepth 1 -name "*.deb" -exec basename {} \;)
        echo "DEB_FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Debian Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.DEB_FILE_NAME }}
        asset_name: ${{ env.DEB_FILE_NAME }}
        asset_content_type: application/vnd.debian.binary-package
